# Server
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/solr_monitoring
spring.datasource.username=postgres
spring.datasource.password=ghofrane123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Optionnel (tu peux supprimer, Hibernate détecte PostgreSQL seul)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_64_CHARS_MIN_CHANGE_ME
jwt.expirationMs=86400000

# Actuator
management.endpoints.web.exposure.include=health,info

# -------------------------
# Solr Monitoring
# -------------------------
# IMPORTANT: baseUrl = http://host:port (PAS /solr)
solr.nodes[0].name=solr-1
solr.nodes[0].baseUrl=http://localhost:8983

solr.nodes[1].name=solr-2
solr.nodes[1].baseUrl=http://localhost:8984

# soit tu mets l'IP si c'est une autre machine,
# soit tu mets localhost:8985 si c'est ton container solr3 exposé sur ton PC

# (si vraiment c'est une autre machine: solr.nodes[2].baseUrl=http://192.168.1.20:8983)

solr.timeouts.connectMs=800
solr.timeouts.readMs=1500
logging.level.org.springframework.security=DEBUG
app.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_123456
app.jwt.expirationMs=86400000
app.frontend.base-url=http://localhost:3000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ghofranesyh@gmail.com
spring.mail.password=osqdoafmvqurquje
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.error.include-message=always
server.error.include-binding-errors=always