# =========================
# Server
# =========================
server.port=8081

# =========================
# PostgreSQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/solr_monitoring
spring.datasource.username=postgres
spring.datasource.password=ghofrane123

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# =========================
# JWT
# =========================
jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_64_CHARS_MIN_CHANGE_ME
jwt.expirationMs=86400000

app.jwt.secret=CHANGE_ME_CHANGE_ME_CHANGE_ME_CHANGE_ME_123456
app.jwt.expirationMs=86400000

# =========================
# Frontend
# =========================
app.frontend.base-url=http://localhost:3000

# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=health,info

# =========================
# Solr Nodes
# =========================
solr.nodes[0].name=solr-1
solr.nodes[0].baseUrl=http://localhost:8983

solr.nodes[1].name=solr-2
solr.nodes[1].baseUrl=http://localhost:8984

# =========================
# Solr Monitoring
# =========================
solr.timeouts.connect-ms=3000
solr.timeouts.read-ms=3000
solr.scheduler.delay-ms=30000

# =========================
# Spring Scheduling
# =========================
spring.task.scheduling.pool.size=2
spring.task.scheduling.thread-name-prefix=solr-health-check-

# =========================
# Mail
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ghofranesyh@gmail.com
spring.mail.password=osqdoafmvqurquje
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# =========================
# Error handling
# =========================
server.error.include-message=always
server.error.include-binding-errors=always

# =========================
# Logging
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.com.example.usermangment.service.SolrHealthService=DEBUG
